# Generated by Django 4.1.2 on 2022-10-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsAPI', '0002_news_image_alter_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
