# Generated by Django 4.1.2 on 2022-10-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsAPI', '0003_remove_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
