# Generated by Django 4.1.2 on 2022-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsAPI', '0008_alter_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='imageUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
